// This script is used to retrieve data generated by `go run generate.go` at backend folder.
// It will generate registry data that will be used by this script to feed into wrangler dev folder, mimicking a R2 bucket.
// This script expects data will be at /tmp/registry.
const fs = require('fs');
const path = require('path');
const { exec } = require('node:child_process');

const directoryPath = '/tmp/registry';

fs.readdir(directoryPath, { recursive: true }, (err, files) => {
  if (err) {
    console.error('Error reading directory:', err);
    return;
  }

  files.forEach(fileName => {
    const realFilePath = path.join(directoryPath, fileName);
    const r2Name = realFilePath.replace(directoryPath, "");

    const cmd = `npx wrangler r2 object put registry-ui-api${r2Name} --file ${realFilePath} --local`
    console.log(cmd)
    exec(cmd, function (err, stdout, stderr) {
      console.log(stdout);
      console.log(stderr);
    });

  });
});
