// This script is used to retrieve data generated by `go run generate.go` at backend folder.
// It will generate registry data that will be used by this script to feed into wrangler dev folder, mimicking a R2 bucket.
// This script expects data will be at /tmp/registry.
const fs = require('fs');
const path = require('path');
const { exec } = require('node:child_process');

const directoryPath = '/tmp/registry';

fs.readdir(directoryPath, { recursive: true }, (err, files) => {
  if (err) {
    console.error('Error reading directory:', err);
    return;
  }

  files.forEach(fileName => {
    const realFilePath = path.join(directoryPath, fileName);
    const r2Name = realFilePath.replace(directoryPath, "");

    fs.lstat(realFilePath, (err, stats) => {

      if(err)
          return console.log(err); //Handle error
      if(stats.isDirectory()) {
        return console.log(`directories are not supported by wrangler api: ${realFilePath}`)
      }

      runCmd(r2Name, realFilePath)
    });
  });
});

const runCmd = (bucketFileName, path) => {
  const cmd = `npx wrangler r2 object put registry-ui-api${bucketFileName} --file ${path} --local`
  exec(cmd, function (err, stdout, stderr) {
    console.log(stdout);
    console.error(stderr);
  });
}
